version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements_docs.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub

# Additional settings for more control
search:
  ranking:
    api/*: -1
    userguide/*: 2
